[project]
name = "windows-app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pillow>=11.3.0",
    "pyinstaller>=6.16.0",
    "pyqt6>=6.9.1",
    "pyqt6-webengine>=6.9.0",
    "requests>=2.32.5",
]
