version: '3.8'

services:
  nvidia-ai-api:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: nvidia-ai-api
    ports:
      - "8000:8000"
    environment:
      - NVIDIA_API_KEY=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
      - PORT=8000
      - HOST=0.0.0.0
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    volumes:
      # Uncomment if you want to mount local .env file
      # - ./.env:/app/.env:ro
      - ./logs:/app/logs
    networks:
      - nvidia-ai-network

networks:
  nvidia-ai-network:
    driver: bridge
