version: '3.8'

services:
  backend:
    build: .
    ports:
      - "8001:8001"
    environment:
      - PYTHONUNBUFFERED=1
      - PORT=8001
      - RABBITMQ_URL=amqp://app:app_password@rabbitmq:5672/
    volumes:
      - .:/app
    restart: unless-stopped
    networks:
      - lct_network

networks:
  lct_network:
    external: true
