version: '3.8'

services:
  backend:
    build: .
    ports:
      - "8002:8002"
    environment:
      - PYTHONUNBUFFERED=1
      - PORT=8002
      - RABBITMQ_URL=amqp://app:app_password@rabbitmq:5672/
      - NVIDIA_API_KEY=${NVIDIA_API_KEY}
    volumes:
      - .:/app
    restart: unless-stopped
    networks:
      - lct_network

networks:
  lct_network:
    external: true
